/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package za.ac.up.cs.cos221;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Ryan
 */
public class clientUpdate extends javax.swing.JFrame {

    main parentForm;
    String name;
    String surname;
    String email;
    String address;
    String address2;
    String district;
    String city;
    String post;
    String phone;
    String store;
    String active;
    
    /**
     * Creates new form clientUpdate
     */
    public clientUpdate(main parent, JTable table) {
        parentForm = parent;
        
        int index = table.getSelectedRow();
        name = (String)table.getValueAt(index, 0);
        surname = (String)table.getValueAt(index, 1);
        email = (String)table.getValueAt(index, 2);
        address = (String)table.getValueAt(index, 3);
        address2 = (String)table.getValueAt(index, 4);
        district = (String)table.getValueAt(index, 5);
        city = (String)table.getValueAt(index, 6);
        post = (String)table.getValueAt(index, 7);
        phone = (String)table.getValueAt(index, 8);
        store = (String)table.getValueAt(index, 9);
        active = (String)table.getValueAt(index, 10);
        
        initComponents();
        
        this.setResizable(false);
        
        jtfName.setText(name);
        jtfSurname.setText(surname);
        jtfEmail.setText(email);
        jtfAddress.setText(address);
        jtfAddress2.setText(address2);
        jtfDistrict.setText(district);
        jtfPost.setText(post);
        jtfPhone.setText(phone);
        jcbxStore.setSelectedItem(store);
        jcbxCity.setSelectedItem(city);
        jcbxActive.setSelectedItem(active);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblName = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jlblSurname = new javax.swing.JLabel();
        jtfSurname = new javax.swing.JTextField();
        jlblEmail = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jlblAddress = new javax.swing.JLabel();
        jtfAddress = new javax.swing.JTextField();
        jlblAddress2 = new javax.swing.JLabel();
        jtfAddress2 = new javax.swing.JTextField();
        jlblDistrict = new javax.swing.JLabel();
        jtfDistrict = new javax.swing.JTextField();
        jlblCity = new javax.swing.JLabel();
        jcbxCity = new javax.swing.JComboBox<>();
        jlblPost = new javax.swing.JLabel();
        jtfPost = new javax.swing.JTextField();
        jlblPhone = new javax.swing.JLabel();
        jtfPhone = new javax.swing.JTextField();
        jlblStore = new javax.swing.JLabel();
        jcbxStore = new javax.swing.JComboBox<>();
        jbtUpdate = new javax.swing.JButton();
        jlblTitle = new javax.swing.JLabel();
        jlblActive = new javax.swing.JLabel();
        jcbxActive = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);

        jlblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblName.setText("First Name:");

        jlblSurname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblSurname.setText("Last Name:");

        jlblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblEmail.setText("Email:");

        jlblAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblAddress.setText("Address:");

        jlblAddress2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblAddress2.setText("Address 2:");

        jlblDistrict.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblDistrict.setText("District:");

        jlblCity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblCity.setText("City:");

        jcbxCity.setModel(populateCities());

        jlblPost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblPost.setText("Postal Code:");

        jlblPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblPhone.setText("Phone:");

        jlblStore.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblStore.setText("Store:");

        jcbxStore.setModel(populateStores());

        jbtUpdate.setText("Update Client Information");
        jbtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateActionPerformed(evt);
            }
        });

        jlblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlblTitle.setText("Edit Client");

        jlblActive.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblActive.setText("Active:");

        jcbxActive.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(155, Short.MAX_VALUE)
                        .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlblName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblAddress2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblSurname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblDistrict)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblPost)
                                    .addComponent(jlblEmail)
                                    .addComponent(jlblCity)
                                    .addComponent(jlblPhone)
                                    .addComponent(jlblStore)
                                    .addComponent(jlblActive))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbxActive, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcbxStore, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfPhone)
                                    .addComponent(jtfPost, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(jcbxCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jlblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jbtUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jlblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblName)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSurname)
                    .addComponent(jtfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblEmail)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAddress)
                    .addComponent(jtfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAddress2)
                    .addComponent(jtfAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblDistrict)
                    .addComponent(jtfDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCity)
                    .addComponent(jcbxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPost)
                    .addComponent(jtfPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPhone)
                    .addComponent(jtfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblStore)
                    .addComponent(jcbxStore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblActive)
                    .addComponent(jcbxActive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jbtUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateActionPerformed
        // TODO add your handling code here:
        String newName = jtfName.getText();
        String newSurname = jtfName.getText();
        String newEmail = jtfName.getText();
        String newAddress = jtfName.getText();
        String newAddress2 = jtfName.getText();
        String newDistrict = jtfName.getText();
        String newCity = (String)jcbxCity.getSelectedItem();
        String newPost = jtfName.getText();
        String newPhone = jtfName.getText();
        String newStore = (String)jcbxStore.getSelectedItem();
        String newActive = (String)jcbxActive.getSelectedItem();
        
        String sql = "UPDATE customer " +
                     "SET";
        
        if (newName != name)
        {
            sql += " first_name = '" + newName + "'";
        }
        
        if (newSurname != surname)
        {
            if (sql == "UPDATE customer " + "SET")
                sql += " last_name = '" + newSurname + "'";
            else
                sql += " AND last_name = '" + newSurname + "'";
        }
        
        if (newEmail != email)
        {
            if (sql == "UPDATE customer " + "SET")
                sql += " email = '" + newEmail + "'";
            else
                sql += " AND email = '" + newEmail + "'";
        }
        
        if (newStore != store)
        {
            if (sql == "UPDATE customer " + "SET")
                sql += " store_id = " + newStore + "";
            else
                sql += " AND store_id = " + newStore + "";
        }
        
        if (newActive != active)
        {
            if (newActive == "True")
                newActive = "1";
            else
                newActive = "0";
            
            if (sql == "UPDATE customer " + "SET")
                sql += " active = " + newActive + "";
            else
                sql += " AND active = " + newActive + "";
        }
        
        if (sql != "UPDATE customer " + "SET")
        {
            Database instance = Database.instance();
            instance.execSQL(sql);
            JOptionPane.showMessageDialog(this, "Client updated successfully.");
            parentForm.refreshClients();
        }
    }//GEN-LAST:event_jbtUpdateActionPerformed

    private DefaultComboBoxModel populateCities()
    {
        Database instance = Database.instance();
        
        String sql = "SELECT city FROM city";
        
        return new DefaultComboBoxModel(instance.returnArray(sql)); 
    }
    
    private DefaultComboBoxModel populateStores()
    {
        Database instance = Database.instance();
        
        String sql = "SELECT store_id FROM store";
        
        return new DefaultComboBoxModel(instance.returnArray(sql)); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtUpdate;
    private javax.swing.JComboBox<String> jcbxActive;
    private javax.swing.JComboBox<String> jcbxCity;
    private javax.swing.JComboBox<String> jcbxStore;
    private javax.swing.JLabel jlblActive;
    private javax.swing.JLabel jlblAddress;
    private javax.swing.JLabel jlblAddress2;
    private javax.swing.JLabel jlblCity;
    private javax.swing.JLabel jlblDistrict;
    private javax.swing.JLabel jlblEmail;
    private javax.swing.JLabel jlblName;
    private javax.swing.JLabel jlblPhone;
    private javax.swing.JLabel jlblPost;
    private javax.swing.JLabel jlblStore;
    private javax.swing.JLabel jlblSurname;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JTextField jtfAddress;
    private javax.swing.JTextField jtfAddress2;
    private javax.swing.JTextField jtfDistrict;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfPhone;
    private javax.swing.JTextField jtfPost;
    private javax.swing.JTextField jtfSurname;
    // End of variables declaration//GEN-END:variables
}
