package za.ac.up.cs.cos221;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class filmsInsert extends javax.swing.JFrame {

    main parentForm;
    
    /**
     * Creates new form filmsInsert
     */
    public filmsInsert(main parent) {
        parentForm = parent;
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTitle = new javax.swing.JLabel();
        jlblFilmTitle = new javax.swing.JLabel();
        jtfTitle = new javax.swing.JTextField();
        jlblDescription = new javax.swing.JLabel();
        jlblReleaseYear = new javax.swing.JLabel();
        jlblLanguage = new javax.swing.JLabel();
        jlblLength = new javax.swing.JLabel();
        jtfLength = new javax.swing.JTextField();
        jtfReplaceCost = new javax.swing.JTextField();
        jlblReplaceCost = new javax.swing.JLabel();
        jlblRentalDur = new javax.swing.JLabel();
        jtfRentalDur = new javax.swing.JTextField();
        jlblOrigLang = new javax.swing.JLabel();
        jlblRating = new javax.swing.JLabel();
        jtfRating = new javax.swing.JTextField();
        jtfSpecial = new javax.swing.JTextField();
        jlblSpecial = new javax.swing.JLabel();
        jcbxOrigLang = new javax.swing.JComboBox<>();
        jspDescription = new javax.swing.JScrollPane();
        jtaDescription = new javax.swing.JTextArea();
        jbtInsert = new javax.swing.JButton();
        jtfRealeaseYear = new javax.swing.JTextField();
        jcbxLanguage = new javax.swing.JComboBox<>();
        jlblRentalRate = new javax.swing.JLabel();
        jtfRentalRate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jlblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlblTitle.setText("Insert Film");

        jlblFilmTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblFilmTitle.setLabelFor(jtfTitle);
        jlblFilmTitle.setText("Title:");

        jlblDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblDescription.setLabelFor(jtfTitle);
        jlblDescription.setText("Description:");

        jlblReleaseYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblReleaseYear.setLabelFor(jtfTitle);
        jlblReleaseYear.setText("Release Year:");

        jlblLanguage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblLanguage.setLabelFor(jtfTitle);
        jlblLanguage.setText("Language:");

        jlblLength.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblLength.setLabelFor(jtfTitle);
        jlblLength.setText("Length:");

        jlblReplaceCost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblReplaceCost.setLabelFor(jtfTitle);
        jlblReplaceCost.setText("Replacement Cost:");

        jlblRentalDur.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblRentalDur.setLabelFor(jtfTitle);
        jlblRentalDur.setText("Rental Duration:");

        jlblOrigLang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblOrigLang.setLabelFor(jtfTitle);
        jlblOrigLang.setText("Original Language:");

        jlblRating.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblRating.setLabelFor(jtfTitle);
        jlblRating.setText("Rating:");

        jlblSpecial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblSpecial.setLabelFor(jtfTitle);
        jlblSpecial.setText("Special Features:");

        jcbxOrigLang.setModel(populateOrgLanguages());

        jspDescription.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jtaDescription.setColumns(20);
        jtaDescription.setLineWrap(true);
        jtaDescription.setRows(5);
        jspDescription.setViewportView(jtaDescription);

        jbtInsert.setText("Insert");
        jbtInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtInsertActionPerformed(evt);
            }
        });

        jcbxLanguage.setModel(populateLanguages());

        jlblRentalRate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblRentalRate.setLabelFor(jtfTitle);
        jlblRentalRate.setText("Rental Rate:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblDescription)
                    .addComponent(jlblFilmTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(jbtInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlblLength)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfLength, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlblReplaceCost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfReplaceCost, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblRating)
                                    .addComponent(jlblSpecial))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfSpecial, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfRating, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jtfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlblTitle)
                            .addGap(113, 113, 113))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jspDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfRealeaseYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jlblReleaseYear)
                        .addGap(235, 235, 235))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblLanguage)
                            .addComponent(jlblOrigLang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbxOrigLang, 0, 227, Short.MAX_VALUE)
                            .addComponent(jcbxLanguage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblRentalDur)
                            .addComponent(jlblRentalRate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfRentalRate)
                            .addComponent(jtfRentalDur, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblFilmTitle)
                    .addComponent(jtfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblDescription)
                    .addComponent(jspDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblReleaseYear)
                    .addComponent(jtfRealeaseYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblLanguage)
                    .addComponent(jcbxLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblOrigLang)
                    .addComponent(jcbxOrigLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblRentalDur)
                    .addComponent(jtfRentalDur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblRentalRate)
                    .addComponent(jtfRentalRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblLength)
                    .addComponent(jtfLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblReplaceCost)
                    .addComponent(jtfReplaceCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblRating)
                    .addComponent(jtfRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSpecial)
                    .addComponent(jtfSpecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {
        parentForm.refreshFilms();
    }

    // Onclick event for Insert Button
    private void jbtInsertActionPerformed(java.awt.event.ActionEvent evt) {
        String title = jtfTitle.getText();
        String desc = jtaDescription.getText();
        String yearReleased = jtfRealeaseYear.getText();
        String duration = jtfRentalDur.getText();
        String rate = jtfRentalRate.getText();
        String length = jtfLength.getText();
        String replaceCost = jtfReplaceCost.getText();
        String rating = jtfRating.getText();
        String special = jtfSpecial.getText();

        Database instance = Database.instance();

        String langSql = "(SELECT language_id " +
        "FROM language " +
        "WHERE name = '" + (String)jcbxLanguage.getSelectedItem() + "')";

        // formatting variables for SQL
        if (desc.length() == 0)
            desc = "NULL";
        else
            desc = "'" + desc + "'";

        if (yearReleased.length() == 0)
            yearReleased = "NULL";
        else
            yearReleased = "'" + yearReleased + "'";

        String orgLangSQL;
        if (((String)jcbxOrigLang.getSelectedItem()).length() != 0)
        {
            orgLangSQL = "(SELECT language_id " +
            "FROM language " +
            "WHERE name = '" + (String)jcbxOrigLang.getSelectedItem() + "')";
        }
        else
            orgLangSQL = "NULL";

        if (length.length() == 0)
            length = "NULL";

        if (rating.length() == 0)
            rating = "NULL";
        else
            rating = "'" + rating + "'";

        if (special.length() == 0)
            special = "NULL";
        else
            special = "'" + special + "'";

        String sql = "INSERT INTO film " +
                     "(title, description, release_year, language_id, original_language_id, " +
                     "rental_duration, rental_rate, length, replacement_cost, rating, special_features) " +
                     "VALUES('" + title + "', " + desc + ", " + yearReleased + ", " + langSql +
                     ", " + orgLangSQL + ", " + duration + ", " + rate + ", " + length + ", " +
                     replaceCost + ", " + rating + ", " + special + ")";
        instance.execSQL(sql);
        JOptionPane.showMessageDialog(this, "Film added successfully.");

        clearForm();

        parentForm.refreshFilms();
    }
    
    // Resets form info
    private void clearForm()
    {
        jtfTitle.setText("");
        jtaDescription.setText("");
        jtfRealeaseYear.setText("");
        jtfRentalDur.setText("");
        jtfRentalRate.setText("");
        jtfLength.setText("");
        jtfReplaceCost.setText("");
        jtfRating.setText("");
        jtfSpecial.setText("");
        jcbxLanguage.setSelectedIndex(0);
        jcbxOrigLang.setSelectedIndex(0);
    }
    
    // Returns ComboBoxModel with language data
    private DefaultComboBoxModel populateLanguages()
    {
        Database instance = Database.instance();
        
        String sql = "SELECT name FROM language";
        
        return new DefaultComboBoxModel(instance.returnArray(sql)); 
    }
    
    // Returns ComboBoxModel with orginal language data
    private DefaultComboBoxModel populateOrgLanguages()
    {
        Database instance = Database.instance();
        
        String sql = "SELECT name FROM language";
        
        String[] temp = instance.returnArray(sql);
        String[] arr = new String[temp.length + 1];
        
        for (int i = temp.length; i > 0; i--)
            arr[i] = temp[i - 1];
        arr[0] = "";
        
        return new DefaultComboBoxModel(arr); 
    }

    private javax.swing.JButton jbtInsert;
    private javax.swing.JComboBox<String> jcbxLanguage;
    private javax.swing.JComboBox<String> jcbxOrigLang;
    private javax.swing.JLabel jlblDescription;
    private javax.swing.JLabel jlblFilmTitle;
    private javax.swing.JLabel jlblLanguage;
    private javax.swing.JLabel jlblLength;
    private javax.swing.JLabel jlblOrigLang;
    private javax.swing.JLabel jlblRating;
    private javax.swing.JLabel jlblReleaseYear;
    private javax.swing.JLabel jlblRentalDur;
    private javax.swing.JLabel jlblRentalRate;
    private javax.swing.JLabel jlblReplaceCost;
    private javax.swing.JLabel jlblSpecial;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JScrollPane jspDescription;
    private javax.swing.JTextArea jtaDescription;
    private javax.swing.JTextField jtfLength;
    private javax.swing.JTextField jtfRating;
    private javax.swing.JTextField jtfRealeaseYear;
    private javax.swing.JTextField jtfRentalDur;
    private javax.swing.JTextField jtfRentalRate;
    private javax.swing.JTextField jtfReplaceCost;
    private javax.swing.JTextField jtfSpecial;
    private javax.swing.JTextField jtfTitle;
}
